/// <reference types="next" />
/// <reference types="next/image-types/global" />

declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_SOLANA_NETWORK?: string
    NEXT_PUBLIC_HELIUS_API_KEY?: string
    NEXT_PUBLIC_SOLANA_FALLBACK_RPC_URL?: string
    SOLANA_RPC_URL?: string
    SOLANA_FALLBACK_RPC_URL?: string
    NEXT_PUBLIC_PROGRAM_ID?: string
    NEXT_PUBLIC_PLATFORM_FEE_RECIPIENT?: string
    APP_BASE_URL?: string
    INDEXER_BASE_URL?: string
    DATABASE_URL?: string
    HELIUS_WEBHOOK_AUTH_TOKEN?: string
    CHAINLINK_CRE_WEBHOOK_URL?: string
    CHAINLINK_CRE_API_KEY?: string
    CHAINLINK_CRE_SIGNING_SECRET?: string
    CHAINLINK_CRE_CALLBACK_SECRET?: string
    CHAINLINK_CRE_REMINDER_WEBHOOK_URL?: string
    CHAINLINK_CRE_REMINDER_API_KEY?: string
    CHAINLINK_CRE_REMINDER_SIGNING_SECRET?: string
    CHAINLINK_CRE_REMINDER_CALLBACK_SECRET?: string
    MOCK_CRE_AUTO_CALLBACK?: string
    MOCK_CRE_FORCE_FAIL?: string
    MOCK_CRE_CALLBACK_BASE_URL?: string
    CRE_REMINDER_DISPATCH_SECRET?: string
    CRE_REMINDER_INTERVAL_DAYS?: string
    OPS_ALERT_WEBHOOK_URL?: string
    CRON_SECRET?: string
    DASHBOARD_PREWARM_TOKEN?: string
    DASHBOARD_PREWARM_ENABLED?: string
    DASHBOARD_PREWARM_PAGES?: string
    CRE_DISPATCH_SECRET?: string
    CRE_STORE_PATH?: string
    UPSTASH_REDIS_REST_URL?: string
    UPSTASH_REDIS_REST_TOKEN?: string
  }
}
